#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


MODE_ORDER = ["mopa_only", "companion_only", "mixed"]
MODE_LABEL = {
    "mopa_only": "MOPA only",
    "companion_only": "Companion instruction only",
    "mixed": "Mixed",
}
MODE_COLOR = {
    "mopa_only": "#005f73",
    "companion_only": "#ca6702",
    "target_only": "#ca6702",
    "mixed": "#2a9d8f",
}
FONT_SIZE = 13


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot M1 overlap benchmark as grouped bars.")
    parser.add_argument("--csv", required=True, help="CSV generated by m1_overlap_bench")
    parser.add_argument("--output", required=True, help="Output png path")
    parser.add_argument("--title", default="M1: MOPA overlap with companion instructions (SVE MLA / ZA MOVA)")
    return parser.parse_args()


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def build_table(rows: list[dict[str, str]]) -> tuple[list[str], dict[tuple[str, str], float]]:
    scenarios: list[str] = []
    table: dict[tuple[str, str], float] = {}

    target_label_map = {
        "sve_mla": "mla",
        "za_mova": "mova",
    }

    for row in rows:
        target_name = row.get("companion") or row.get("target")
        if target_name is None:
            raise SystemExit("csv is missing 'companion'/'target' column")

        mopa_count = row["mopa_count"]
        target_count = row.get("companion_count") or row.get("target_count")
        if target_count is None:
            raise SystemExit("csv is missing 'companion_count'/'target_count' column")

        target_label = target_label_map.get(target_name, target_name.lower())
        scenario = f"{mopa_count} mopa + {target_count} {target_label}"
        if scenario not in scenarios:
            scenarios.append(scenario)

        mode = row["mode"]
        if mode == "target_only":
            mode = "companion_only"
        table[(scenario, mode)] = float(row["ns_per_iter"])

    return scenarios, table


def main() -> None:
    args = parse_args()
    csv_path = Path(args.csv)
    output = Path(args.output)

    rows = load_rows(csv_path)
    if not rows:
        raise SystemExit(f"no rows found in {csv_path}")

    scenarios, table = build_table(rows)

    x = np.arange(len(scenarios))
    width = 0.24
    offsets = np.linspace(-width, width, len(MODE_ORDER))

    fig, ax = plt.subplots(figsize=(11, 5.5))
    fig.patch.set_facecolor("#f7f4ef")

    for offset, mode in zip(offsets, MODE_ORDER):
        values = [table.get((scenario, mode), 0.0) for scenario in scenarios]
        ax.bar(
            x + offset,
            values,
            width=width,
            label=MODE_LABEL[mode],
            color=MODE_COLOR[mode],
            edgecolor="white",
            linewidth=1.0,
            alpha=0.92,
        )

    ax.set_title(args.title, fontsize=FONT_SIZE, fontweight="bold")
    ax.set_ylabel("ns / iteration", fontsize=FONT_SIZE, fontweight="bold")
    ax.set_xticks(x, scenarios, fontsize=FONT_SIZE)
    ax.tick_params(axis="y", labelsize=FONT_SIZE)
    ax.grid(axis="y", linestyle="--", linewidth=0.8, alpha=0.25)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.legend(frameon=False, ncol=3, loc="upper center", bbox_to_anchor=(0.5, 1.13), fontsize=FONT_SIZE)

    fig.tight_layout()
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=220, bbox_inches="tight")
    fig.savefig(output.with_suffix(".pdf"), bbox_inches="tight")
    print(f"wrote {output}")
    print(f"wrote {output.with_suffix('.pdf')}")


if __name__ == "__main__":
    main()
