#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from gemm_bench_common import BENCH_OUT_DIR


BACKEND_ORDER = ["smelt", "ir2a-asm", "ir2a-bin", "ir2c", "armpl", "libxsmm", "openblas"]
BACKEND_LABELS = {
    "smelt": "SMELT (local)",
    "ir2a-asm": "IR2A ASM, direct kernel",
    "ir2a-bin": "IR2A BIN, direct kernel",
    "ir2c": "IR2C, direct kernel",
    "armpl": "ArmPL 26.01, LP64",
    "libxsmm": "LIBXSMM",
    "openblas": "OpenBLAS",
}
BACKEND_COLORS = {
    "smelt": "#17375e",
    "ir2a-asm": "#345995",
    "ir2a-bin": "#5d7fb9",
    "ir2c": "#8fb7d8",
    "armpl": "#7dbb4c",
    "libxsmm": "#56b1d8",
    "openblas": "#6b4c9a",
}
BACKEND_HATCHES = {
    "smelt": "..",
    "ir2a-asm": "**",
    "ir2a-bin": "\\\\",
    "ir2c": "oo",
    "armpl": "////",
    "libxsmm": "++",
    "openblas": "||",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate grouped bar charts for GEMM benchmark results.")
    parser.add_argument(
        "--csv",
        default=str(BENCH_OUT_DIR / "gemm_perf_compare.csv"),
        help="merged CSV generated by run_gemm_perf_compare.py",
    )
    parser.add_argument(
        "--output",
        default=str(BENCH_OUT_DIR / "gemm_perf_compare.png"),
        help="output image path",
    )
    parser.add_argument(
        "--title",
        default="SME-GEMM Small Matrix Performance Comparison",
        help="figure title",
    )
    return parser.parse_args()


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    return [row for row in rows if row.get("status") == "ok"]


def collect_sizes(rows: list[dict[str, str]]) -> list[int]:
    return sorted({int(row["m"]) for row in rows})


def present_backends(rows: list[dict[str, str]]) -> list[str]:
    return [backend for backend in BACKEND_ORDER if any(row["backend"] == backend for row in rows)]


def metric_table(rows: list[dict[str, str]], metric: str, backends: list[str]) -> dict[str, dict[int, float]]:
    table: dict[str, dict[int, float]] = {backend: {} for backend in backends}
    for row in rows:
        backend = row["backend"]
        if backend not in table:
            continue
        table[backend][int(row["m"])] = float(row[metric])
    return table


def draw_grouped_bars(
    ax: plt.Axes,
    sizes: list[int],
    backends: list[str],
    table: dict[str, dict[int, float]],
    ylabel: str,
    *,
    lower_is_better: bool = False,
) -> None:
    x = np.arange(len(sizes))
    width = min(0.84 / max(len(backends), 1), 0.16)
    offsets = np.linspace(-0.5 * width * (len(backends) - 1), 0.5 * width * (len(backends) - 1), len(backends))

    for offset, backend in zip(offsets, backends):
        values = [table[backend].get(size, 0.0) for size in sizes]
        ax.bar(
            x + offset,
            values,
            width=width,
            label=BACKEND_LABELS[backend],
            color=BACKEND_COLORS[backend],
            edgecolor="white",
            linewidth=1.0,
            hatch=BACKEND_HATCHES[backend],
            alpha=0.92,
        )

    ax.set_ylabel(ylabel, fontweight="bold")
    ax.set_xticks(x, [str(size) for size in sizes])
    ax.grid(axis="y", linestyle="--", linewidth=0.8, alpha=0.25)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    if lower_is_better:
        ax.set_title("Average Time Per GEMM (lower is better)", loc="left", fontweight="bold", fontsize=12)
    else:
        ax.set_title("GFLOPS (higher is better)", loc="left", fontweight="bold", fontsize=12)


def main() -> None:
    args = parse_args()
    csv_path = Path(args.csv)
    output_path = Path(args.output)
    rows = load_rows(csv_path)
    if not rows:
        raise SystemExit(f"no successful benchmark rows found in {csv_path}")

    sizes = collect_sizes(rows)
    backends = present_backends(rows)
    gflops = metric_table(rows, "gflops", backends)
    avg_ns = metric_table(rows, "avg_ns", backends)

    plt.style.use("default")
    fig, axes = plt.subplots(2, 1, figsize=(18, 10), sharex=True, gridspec_kw={"height_ratios": [3, 2]})
    fig.patch.set_facecolor("#fbfaf8")

    draw_grouped_bars(axes[0], sizes, backends, gflops, "GFLOPS (DP)")
    draw_grouped_bars(axes[1], sizes, backends, avg_ns, "Average ns", lower_is_better=True)
    axes[1].set_xlabel("M = N = K", fontweight="bold")

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(
        handles,
        labels,
        loc="upper center",
        ncol=min(3, max(1, len(backends))),
        frameon=False,
        bbox_to_anchor=(0.5, 0.98),
        fontsize=11,
        handlelength=1.4,
        handletextpad=0.4,
        columnspacing=1.8,
    )
    fig.suptitle(args.title, fontsize=18, fontweight="bold", y=0.995)
    fig.tight_layout(rect=[0.02, 0.04, 0.98, 0.90])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    fig.savefig(output_path.with_suffix(".svg"), bbox_inches="tight")
    print(f"wrote {output_path}")
    print(f"wrote {output_path.with_suffix('.svg')}")


if __name__ == "__main__":
    main()
